name = "cf-ai-chat"
main = "src/worker.js"
compatibility_date = "2025-08-25"

[ai]
binding = "AI"

# KV 存储配置（可选，用于聊天历史）
# 需要先在 Cloudflare Dashboard 创建 KV 命名空间
# 然后替换下面的 id 和 preview_id
[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "8425f1689efb425f81771d691a648e80"
preview_id = "8425f1689efb425f81771d691a648e80"

# 环境变量配置
# 部署前请修改为安全的密码
[vars]
CHAT_PASSWORD = "jinlian144239"






